services:
  mail-connect:
    image: "git.pontusmail.org/librecloud/web:latest"
    container_name: mail-connect
    env_file: ".env"
    ports:
      - "6723:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/app"