services:
  mail-connect:
    image: "git.pontusmail.org/librecloud/mail-connect:latest"
    container_name: mail-connect
    env_file: ".env"
    restart: always
    ports:
      - "6723:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/app"